### ISSUE TITLE
RSD can be both in cyrilic and latin script

### ISSUE THREAD

**Issue by eboye** [magarrent/laravel-currency-formatter#1]
Cool library! It can be really useful. I'll definitely bookmark it for my future projects. But one note:

RSD can be both in cyrilic and latin script

In Serbia, we use RSD, Din and Дин

Where Дин and Din are exactly the same just written in different script. I'm not sure how it would be made to choose which one to use, but maybe other currencies can have multiple scripts.

**Comment by magarrent** [comment]
Hello @eboye ! Nice to hear that! I didn't know it.

I've added a new function (v1.0.2) called `setSymbol`, so now you can modify and add a custom Symbol to your currency format:


```php
Currency::currency("RSD")->setSymbol("Din")->format(123456789)  // 123.456.789,00 Din
```

**Comment by eboye** [comment]
Great, thanks!
